version: '3'

services: 
  openvpn:
    build:
      context: .
    container_name: openvpn-with-ldap
    image: trantect/openvpn-rpi
    cap_add:
     - NET_ADMIN
    restart: always
    ports: 
      - 1194:1194/udp
    devices:
      - "/dev/net/tun:/dev/net/tun"
    volumes: 
      - "${PWD}/config:/etc/openvpn"