version: '2'
services:
  chart-museum:
    restart: always
    image: chartmuseum/chartmuseum:latest
    container_name: chart-museum
    volumes:
    - ~/.helm/repository/local:/data/charts
    ports:
    - "80:8080"
    environment:
    - STORAGE=local
    - STORAGE_LOCAL_ROOTDIR=/data/charts
    - PORT=8080